### ISSUE TITLE
snp not used in analysis?

### ISSUE THREAD

**Issue by basel-maher** [xqwen/fastenloc#10]
Hi,

I'm having a strange issue where a variant is not being used in the analysis, as it is not in the SNP based output.
The variant is in both GTEx and my GWAS. Furthermore, I'm getting results for the SNP in some tissues, but not all (in my case, thyroid is my tissue of interest). In this case, I used the pre-computed GTEx file that you provide.

I checked, and the variant in question (chr11_68450822_C_T_b38)   seems to be an eQTL in thyroid, and has a MAF of ~0.24. 
Any ideas why its not being used for thyroid (and some other tissues)?

Thanks

**Comment by xqwen** [comment]
This question is related to the provided eQTL annotation based on the GTEx data. The selection criteria for each SNP in each tissue is based on the multi-SNP fine-mapping results. I am happy to explain more about the selection criteria. But just to be clear, when you say "chr11_68450822_C_T_b38 seems to be an eQTL in thyroid", is it based on single SNP association testing results?

**Comment by basel-maher** [comment]
It is based on "all snp-gene associations" from GTEx. I'm guessing that the annotation takes into account only the "significant" variant-gene associations as calculated by GTEx?

I guess my question is what determines which variants are outputted in the SNP based analyses? 

Thanks!

**Comment by xqwen** [comment]
The criteria is based on multi-SNP association analysis. If a SNP is considered to be a member of a *signal cluster*, it will be annotated. The relevant details can be found in the DAP-G paper or dap repo.

**Comment by basel-maher** [comment]
Hi,

I'm still confused as to why some GWAS variants are chosen as members of a signal cluster and others aren't. Does the eQTL cluster define the GWAS signal cluster? For example, if I have a gwas for a phenotype, and I'm colocalizing with eQTL for a gene in two tissues, why do the signal clusters differ between them? If the eQTL are in close proximity (or even the same), shouldn't the signal clusters for the GWAS be similar? i.e. a large overlap between SNPs defining a cluster in each analysis

**Comment by xqwen** [comment]
All variants are used in the enrichment estimation procedure. But for computing regional colcoalization probabilities (RCPs) only signal clusters identified in eQTL mapping are used.

It should be clear that the genomic region harboring a colocalized variant must be noteworthy in eQTL analysis. It is therefore natural to use the signal cluster inferred in the eQTL mapping to define the candidate genomic regions.  

There are many reasons that signal clusters for eQTLs can be different. See references for tissue-specific eQTLs. 

I think your viewpoint is valid, but in practice, we typically don't have detailed information, e.g., individual-level data, from GWAS.  It is rather a practical choice to rely on eQTL data for defining signal clusters.
