### ISSUE TITLE
fastENLOC analysis not reproducible when executed on multiple cores?

### ISSUE THREAD

**Issue by probalica19** [xqwen/fastenloc#15]
Hi, 

I have noticed that these two commands yield slightly different results.

```
fastenloc -g sim_data/gwas.pip.gz -e sim_data/eqtl.vcf.gz -prefix fastenloc_out/sim -tv 30000000 --all
```
and
```
fastenloc -g sim_data/gwas.pip.gz -e sim_data/eqtl.vcf.gz -prefix fastenloc_out/sim -tv 30000000 --all -thread 8
```

This commands and input files are from `fastenloc/promise_and_limitation_paper/empirical_power_evaluation` directory. When I compare my results to the ones in `fasteloc_output` folder in the same location, only the files produced by the first of the above mentioned commands yields the same results. 

Is this behavior expected?

Thanks!

probalica19

**Comment by xqwen** [comment]
Yes, the multiple imputation procedure in enrichment estimation is a stochastic sampling procedure. Small variations in enrichment results are expected.
