### ISSUE TITLE
fastENLOC doesn't fail when 0 loci is found

### ISSUE THREAD

**Issue by probalica19** [xqwen/fastenloc#18]
Hi, 

I am running fastENLOC on a large scale and I am noticing that for some samples when there are no overlaps between GWAS loci and eQTL loci, the tool doesn't fail but keeps on running, which makes it really hard to debug.

Here is an example:

```
Computing colocalization probabilities ...

Processing eQTL annotations ...
read in 288 SNPs, 16 eQTL signal clusters, 2.1 expected eQTLs

Processing complex trait data ...
read in 288 SNPs (eQTL+gwas), 0 GWAS loci, 0.0 expected hits
```
and the tool goes on forever. I noticed the same behavior when there are no eQTL loci. 

Can this be fixed, or can you recommend a way of handing this? 

Just as a note, I am working with predefined regions, so in order to save space I am using GTEx eQTL annotation files  that I have previously subsetted to a region of interest using tabix. 

Thank you in advance!

probalica

**Comment by xqwen** [comment]
Thanks for reporting this.  We will fix this issue in the new version.

William

**Comment by probalica19** [comment]
Hi William, 

Thank you for your response. I see that fastENLOC beta version 2.0 has been published. Has this issue been fixed in the new version?

Also, did you maybe notice that the same issue persists if only a single SNP is found (i.e. `grep tissue_name eqtl_annotation_file` returns only one line)? 

Thanks!

probalica19

**Comment by xqwen** [comment]
We have not committed the changes for the fix. The published version only adds the new features. This is definitely on our todo list. Our goal is to revamp the error detection and reporting in fastENLOC.

**Comment by probalica19** [comment]
Dear William,

I really appreciate  your response. I just want to confirm what I mentioned in the previous comment - my testing showed that fastenloc will encounter the same issue if there is only a single SNP in eQTL annotation file for the given tissue. In other words, fastenloc will log that has found 0 eQTL annotations and run indefinitely, although manual inspection of the eQTL annotation file finds exactly one SNP with an annotation for that tissue. 

Hope this helps, 

probalica19

**Comment by emlynarski** [comment]
Dear William,

Thank you for your effort with resolving this issue! I have a few follow-up questions I’m hoping you can help with:

1.	Do you have an estimated timeline for when the changes for the fix will be committed?
2.	Do you have suggested workarounds that we can use in the meantime?

Thanks!
emlynarski

**Comment by xqwen** [comment]
Issue fixed in the new release (version 2)
