### ISSUE TITLE
Correct shrinkage value

### ISSUE THREAD

**Issue by rbutleriii** [xqwen/fastenloc#20]
Hi,

Is there a resource on guidance for choosing an appropriate shrinkage value? Should it be calibrated based on the expected hit number or the `*enloc.enrich.out` values?

Thanks

**Comment by xqwen** [comment]
The shrinkage parameter can be interpreted as a prior for the enrichment parameter. Based on our experience of eQTL analysis with various complex and molecular traits, the default prior N(0,1) seems adequate. In general, I'd consider that prior variance ranging from 0.5 to 10 (or shrinkage from 2 to 0.1) reasonable. Values outside this range, I think, could be too conservative or liberal.

Hope this helps.

William

**Comment by rbutleriii** [comment]
Thanks!
