### ISSUE TITLE
Can fastenloc apply to two different populations?

### ISSUE THREAD

**Issue by JFF1594032292** [xqwen/fastenloc#21]
Hi,
I'm using fastenloc to integrate an eQTL data and a GWAS data, however they are from different population (Asian eQTL and european GWAS).
I wonder if fastenloc can handle this situation?  Or there are some ways to add two populations' LD information to the procedure?

Jiang

**Comment by xqwen** [comment]
Technically, you can, i.e., you would not get any error messages from the program. But mismatching LD is a violation of the analysis assumption and likely cause power loss to detect colocalizations (but unlikely false positives). 

There are some discussions/experiments in "mismatching LD structures" section of [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7820626/). We are still in the process of searching a better solution.

William

**Comment by JFF1594032292** [comment]
Thanks for your reply!  This paper also helped greatly!
