### ISSUE TITLE
Using torus to get GWAS PIP: How to determine the prior probability?

### ISSUE THREAD

**Issue by qxliu686** [xqwen/fastenloc#25]
Hi ! 
Prof.  @xqwen 

I am preparing **GWAS PIP input** using **torus** . 
When I run the example code "torus -d Height.torus.zval.gz --load_zval -dump_pip Height.gwas.pip" , 
I noticed there are 4 columns in the output file "Height.gwas.pip" . 
I think the fourth column is the **prior probability** for a SNP to be causal, but how is this value determined? 
#
Thank you so much for your reply

**Comment by xqwen** [comment]
It is estimated via the EM algorithm described in the original AOAS paper.
