### ISSUE TITLE
static binary file of version 2

### ISSUE THREAD

**Issue by Takahiro0113** [xqwen/fastenloc#26]
Hi,

I'm trying to use your fantastic software fastENLOC version 2, but to my regret the compiled binary file doesn't work well in my environment.
I encountered a similar thread (https://github.com/xqwen/fastenloc/issues/3) and found that static linked version of compiled Linux executable "fastenloc.static" you have added worked well.

To my understanding this is a binary file for fastENLOC (version 1), so would you add the similar static version of compiled Linux executable in fastENLOC version 2?
Thank you in advance.

Taka

**Comment by xqwen** [comment]
The static linked linux executables are added for both master and dev branches.
