### ISSUE TITLE
VCF file queston

### ISSUE THREAD

**Issue by basel-maher** [xqwen/fastenloc#5]
Hello,
is the "Multi-tissue eQTL annotation with hg38 position ID" file based on significant cis-eQTL or ALL cis-eQTL associations?

Furthermore, where can I find a VCF file with all GTEx V8 annotations, in case I want to derive my own annotations?

Thanks

**Comment by xqwen** [comment]
The annotated SNPs are from the multi-SNP analysis of GTEx eQTL data. There is no "significance" filter for genes or annotated SNPs. But the GTEx does put an allele frequency filter, i.e., all annotated SNPs should have sample allele frequency > 0.03 in the GTEx samples.

**Comment by xqwen** [comment]
For all GTEx variants, you can find the files in gtexportal.org-> data download -> eQTL Tissue-Specific All SNP Gene Associations

I am not completely sure if there is any (lenient) allele frequency filter applied there. But it should contain a superset of variants.
