### ISSUE TITLE
what are the total variants?

### ISSUE THREAD

**Issue by basel-maher** [xqwen/fastenloc#6]
For the -total_variants flag, what are the total variants?

If I am using GTEx data and some GWAS, are the total variants the max number of variants in the two datasets? Or is it the number of variants genotyped by GTEx (~46 million)? For example, the VCF files you provide doesn't have all variants genotyped by GTEx. So would it be the number of SNPs in the VCF or the total number of genotyped GTEx variants?

**Comment by xqwen** [comment]
Good questions! I apologize that we did not make it clear in the document. The total_variants refers to the total variants investigated in the ***GWAS***.  The annotated eQTL SNPs can be a subset. In cases that the full GWAS SNPs are input into fastENLOC, you don't need to specify this number. Some users only proved fine-mapped GWAS regions for colocalization analysis. In such a case, it is critical to specify "total_variants", such that all probabilities are calibrated at the genome-wide scale.  The number of eQTL annotated is not a concern here. Unannotated SNPs in the GWAS file but not in the eQTL file will be treated as non-eQTL SNP.

**Comment by basel-maher** [comment]
Thanks for the reply.
What if the number of eQTL is much larger than the number of GWAS snps? Does the eQTL data have to be trimmed prior to colocalization?

**Comment by xqwen** [comment]
You don't have to. The annotated SNPs in the eQTL file are assumed to be a part of the GWAS investigation. If they do not appear in the GWAS file, fastENLOC simply "imputes" that they are not associated with the complex trait of interest (i.e., association PIP = 0). 

We do recommend to perform formal imputation procedures (either at the genotype level or at the summary-statistics level) to ensure that the SNPs in eQTL and GWAS input files are matched up.
