### ISSUE TITLE
GWAS loci not detected

### ISSUE THREAD

**Issue by basel-maher** [xqwen/fastenloc#7]
I'm trying to run my data after completing all previous steps. However, I keep getting the following line when running fastenloc -eqtl gtex_v8.eqtl_annot.vcf.gz -gwas morris.pip.gz -total_variants 17000000 -t Thyroid

Processing complex trait data ... 
read in 13921173 SNPs (eQTL+gwas), 22 GWAS loci, 22.0 expected hits

As you can see, only 22 loci are considered. However, I have ~1700 loci, which I added using format2torus.pl
Do you have any idea what might be causing this? 
Thanks

**Comment by basel-maher** [comment]
i think the issue is that only 22 loci are annotated by format2.torus, while there are thousands of loci, even according to a manual check of eur_ld.hg38.bed

**Comment by xqwen** [comment]
Yes, that looks like the problem. Before you run format2torus, make sure the genomic location is sorted (i.e., chr 1 to 22, and in each chromosome, the position is increasing).

**Comment by basel-maher** [comment]
Genomic location is ordered by chromosome and position, so I'm not sure that's the problem.

Data is also in this format:
chr1_55326_T_C_b38	1	55326	-1.51410188761928
chr1_55351_T_A_b38	1	55351	-1.47579102817917
chr1_64904_T_G_b38	1	64904	-2.04353000743986
chr1_64908_A_G_b38	1	64908	-1.05812161768478

**Comment by basel-maher** [comment]
also, do you remove variants with no locus definition in eur_ld.hg38.bed? For example, I have chr12_12858_C_G_b38 in the GWAS data and the first chr12 locus is:
chr12	44631	971165

**Comment by xqwen** [comment]
Can you tell me which formatting script you are using? 

You could write your own formatting script to add those SNPs as a new block.

**Comment by basel-maher** [comment]
I am using my own formatting script, as I had no success with format2torus.pl
I found several hundred SNPs across a few chromosomes which did not fall into a locus as defined by eur_ld.hg38.bed

I have removed them from the analysis, as I'm not sure if each set would fall into its own locus or is in high LD with one of the annotated loci.

**Comment by xqwen** [comment]
Cool! I am still not sure where you download format2torus.pl script. Can you give me the link? Also, do you want me to link your formatting script?  Thanks!

**Comment by basel-maher** [comment]
format2torus.pl was from a previous issue posted here: https://github.com/xqwen/fastenloc/issues/2

As for my script, it's an ad hoc R script. The following is the main loop:

```
#read in LD locus annotations
loc = read.table("eur_ld.hg38.bed", stringsAsFactors = F, header = T)
loc$loc = paste0("Loc",rownames(loc))

#format gwas object
gwas$pos_hg38 = as.numeric(gwas$pos_hg38)
gwas$loc = NA

#create empty vector for output
val = nrow(morris_sub)
output = c(rep(NA,val))

#for each defined locus, find gwas variants that fall into it, by matching chrom and pos
for(i in 1:nrow(loc)){
  x = which(gwas$chr_hg38 == loc$chr[i] & gwas$pos_hg38 >= loc$start[i] & gwas$pos_hg38 <= loc$stop[i])
  output[x] = loc$loc[i]
  print(i)
}

#add locus column to gwas object
gwas$loc = output

#remove variants with no locus annotation
gwas = gwas[-which(is.na(gwas$loc)),]
```

**Comment by xqwen** [comment]
Thanks! Pretty cool to use which() function.
