### ISSUE TITLE
multiple genes in output

### ISSUE THREAD

**Issue by basel-maher** [xqwen/fastenloc#8]
fastenloc output includes multiple results for each gene, in the format of
ENSG00000xxxx:1
ENSG00000xxxx:2

Can you please explain the difference between these?
Thanks

**Comment by xqwen** [comment]
There are multiple independent eQTLs for ENSG00000xxxx, they are denoted by ":1", ":2",... The colocalization is performed with respect to each eQTL signal.

**Comment by basel-maher** [comment]
thanks!
